http_archive(
        name = "io_bazel_rules_go",
        url = "https://github.com/bazelbuild/rules_go/releases/download/0.10.3/rules_go-0.10.3.tar.gz",
        sha256 = "feba3278c13cde8d67e341a837f69a029f698d7a27ddbb2a202be7a10b22142a",
)
http_archive(
        name = "bazel_gazelle",
        url = "https://github.com/bazelbuild/bazel-gazelle/releases/download/0.10.1/bazel-gazelle-0.10.1.tar.gz",
        sha256 = "d03625db67e9fb0905bbd206fa97e32ae9da894fe234a493e7517fd25faec914",
)
git_repository(
        name = "io_bazel_rules_docker",
        remote = "https://github.com/bazelbuild/rules_docker.git",
        tag = "v0.4.0",
)

#
# Golang
#

load(
        "@io_bazel_rules_go//go:def.bzl",
        "go_rules_dependencies",
        "go_register_toolchains",
        "go_repository"
)

go_rules_dependencies()
go_register_toolchains(
    go_version = "1.10.1",
)

# Ensure @org_golang_google_grpc matches my vendored copy
go_repository(
    name = "org_golang_google_grpc",
    importpath = "google.golang.org/grpc",
    commit = "95869d0274dc5f61cad15f9ef42e060b9c9e0a3a",
    build_file_proto_mode = "disable"
)

#
# Gazelle
#
load(
    "@bazel_gazelle//:deps.bzl",
    "gazelle_dependencies"
)

gazelle_dependencies()

#
# Docker
#

load(
        "@io_bazel_rules_docker//go:image.bzl",
        _go_image_repos = "repositories",
)

_go_image_repos()
